### ISSUE TITLE
px-app will not work with google-map kml

### ISSUE THREAD

**Issue by vietanh85** [PredixDev/px-theme#5]
I'm trying to to integrate google-map component with predix-seed and had a problem when trying to display polyline to the map, I figured out the problem came from these lines of code:

``` css
/**
 * Remove border when inside `a` element in IE 8/9/10. Make images shrink from their largest size.
 */
img {
  max-width: 100%;
  border: 0; }
```

Please checkout the links bellow (the problem only occurred when using chrome):
You will not see the polyline with this:
http://google-map-px-app.run.aws-usw02-pr.ice.predix.io/sample-data/map-with-px-app.html

But you can see the polyline after remove px-app:
http://google-map-px-app.run.aws-usw02-pr.ice.predix.io/sample-data/map-without-px-app.html

My sugession is to change the css code to:

``` css
/**
 * Remove border when inside `a` element in IE 8/9/10. Make images shrink from their largest size.
 */
img:not(:google-map) {
  max-width: 100%;
  border: 0; }
```

If you want I can send a pull request.
